name: hmm_interaction
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pyyaml
  - pytest
  - scikit-learn
  - hmmlearn
  - joblib
  - kneed
  - pingouin
  - statsmodels
  - openpyxl
